#pragma once

#define EASYDROPLETSPEED 5
#define MEDIUMDROPLETSPEED 10
#define HARDDROPLETSPEED 15

#define EASYENEMYSPEED 2
#define MEDIUMENEMYSPEED 3
#define HARDENEMYSPEED 4

#define EASYENEMYRANGE 250
#define MEDIUMENEMYRANGE 350
#define HARDENEMYRANGE 500


#define EASYENEMYCOOLDOWN 50
#define MEDIUMENEMYCOOLDOWN 35
#define HARDENEMYCOOLDOWN 20

#define PLAYERSPEED 5
